# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_body_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='1', unique=True),
            preserve_default=False,
        ),
    ]
