# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photoCredit',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
