# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_photocredit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photoCredit',
            new_name='photo_credit',
        ),
    ]
