# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170917_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='name',
            new_name='email_name',
        ),
        migrations.AddField(
            model_name='email',
            name='email_subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
