# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_credit',
        ),
    ]
