# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 22:25
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
